<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 5.0.1 (Python 3.10.4 on win32)" generated="20220517 22:30:41.239" rpa="false" schemaversion="3">
<suite id="s1" name="Login" source="c:\Automacao\automacaoapp\tests\login.robot">
<test id="s1-t1" name="Deve fazer login" line="9">
<kw name="Open Session" library="base" type="SETUP">
<kw name="Open Application" library="AppiumLibrary">
<arg>http://localhost:4723/wd/hub</arg>
<arg>automationName=UiAutomator2</arg>
<arg>platformName=Android</arg>
<arg>deviceName=Simulador</arg>
<arg>app=${EXECDIR}/app/cliente.apk</arg>
<arg>appActivity=br.com.mobile.armazempb.ui.splash.SplashScreenActivity</arg>
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | no     | alias             |</doc>
<kw name="Capture Page Screenshot" library="AppiumLibrary">
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<msg timestamp="20220517 22:30:43.709" level="FAIL">No application is open</msg>
<status status="FAIL" starttime="20220517 22:30:43.706" endtime="20220517 22:30:43.726"/>
</kw>
<msg timestamp="20220517 22:30:43.727" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20220517 22:30:43.729" level="FAIL">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: The application at 'c:\Automacao\automacaoapp\tests/app/cliente.apk' does not exist or is not accessible
</msg>
<status status="FAIL" starttime="20220517 22:30:41.541" endtime="20220517 22:30:43.729"/>
</kw>
<status status="FAIL" starttime="20220517 22:30:41.541" endtime="20220517 22:30:43.730"/>
</kw>
<status status="FAIL" starttime="20220517 22:30:41.540" endtime="20220517 22:30:43.731">Setup failed:
WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: The application at 'c:\Automacao\automacaoapp\tests/app/cliente.apk' does not exist or is not accessible
</status>
</test>
<status status="FAIL" starttime="20220517 22:30:41.242" endtime="20220517 22:30:43.735"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Login">Login</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20220517 22:30:43.727" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
</errors>
</robot>
